{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ssu-catalog.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ssu-catalog.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ssu-catalog.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: 60s
{{- end }}
